FROM oven/bun:1.1.0 AS builder

WORKDIR /app

COPY bun.lockb package.json ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build   # must output /app/dist

FROM scratch AS export
COPY --from=builder /app/dist /dist
